# Generated by Django 6.0.1 on 2026-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # noqa: E501
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')), # noqa: E501
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
